permalink: /blog/:title
sakura-jekyll-version: 0.9.0
# Information required for feed
title: Constellation # Change this to your site name.
description:
url: 'https://squeuei.github.io'
author:
    twitter: # twitter user name here
license: '<a href="http://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer" >CC BY 4.0</a>'
date_format: "%FT%T%:z"
timezone: Asia/Tokyo

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "squeuei" # Set this to default author



# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
twitter:
    username:

# Includes an icon in the 'ABOUT' page for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss: True # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

jekyll-archives:
  enabled: 
    - tags
    - categories
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

feed:
  posts_limit: 50

gems:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives
